# Generated by Django 3.2.9 on 2021-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='file',
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
